---
auto_deploy: true
context: release-cluster
domain: rls.sh
repo_name: nielthiart/release-configmap-test
environment_templates:
- name: ephemeral
- name: permanent
resources:
  cpu:
    limits: 1000m
    requests: 100m
  memory:
    limits: 1Gi
    requests: 100Mi
  replicas: 1
services:
- name: busyexample
  image: nielthiart/release-configmap-test/busyexample
  has_repo: true
  build:
    context: "."
    dockerfile: "./Dockerfile"
  command:
  - sh
  args:
  - "-c"
  - ls -laF /etc/file1.txt && ls -laF /etc/configmaptest/file2.txt && sleep infinity
  configmap:
  - mount_path: "/etc/file1.txt"
    repo_path: "./file1.txt"
    name: file-one
  - mount_path: "/etc/configmaptest/file2.txt"
    repo_path: "./file2.txt"
    name: file-two
workflows:
- name: setup
  parallelize:
  - step: services
    tasks:
    - services.busyexample
- name: patch
  parallelize:
  - step: services
    tasks:
    - services.busyexample
- name: teardown
  parallelize:
  - step: remove-environment
    tasks:
    - release.remove_environment
